### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by smaragdus** [martinrotter/textosaurus#28]
@martinrotter 

Currently (as of version **2018.03.26**) **Textosaurus** comes with three built-in themes:

- **Textosaurus**
- S**olarized Light**
- **Solarized Dark**

I use the **Default** one because I am bored with **Solarized** ones. My question- would it be possible to port to **Textosaurus** at least one more theme? Several possible examples:

- [City Lights](https://atom.io/themes/city-lights-syntax)
- [Doc Green](https://atom.io/themes/doc-green-syntax)
- [Monokai Neo](https://atom.io/themes/monokai-neo-syntax)
- [Seti](https://atom.io/themes/seti-syntax)

If I had to choose one theme it would probably be [Monokai Neo](https://github.com/skylerlee/monokai-neo-syntax).

If you don't have time to mess with  themes close this issue. For me changing themes from time to time is refreshing.

**Comment by martinrotter** [comment]
I added Monokai Neo theme. Please, test it.

Note that textilosaurus uses a bit simplified style model which does not allow to use many contextual substyles (for example "identifiers" are substyled very rarely and also some other parts of displayer source texts). So, the result may look a bit flat (in a sense that smaller subset of colors is used when compared to [this](https://i.github-camo.com/fca1ffdc0bee096dc9d75737e4320885a573194f/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f363738393439312f32393234323334362d30373462653561612d376662652d313165372d393939362d3031616338353937623030342e706e67)). This has performance reasons.

Also, some lexers/languages (see "Language" menu in Textosaurus) do not have substyles defined at all. I add them one by one as I need them. So for example C++ will display nicely colored keywords but C# won't because I did not code them in Textosaurus yet. If you often use some particular Language highlighting (for example C#, HTML, whatever) and you feel that your code is not styled with colors properly, then create bug report and list all Languages you want me to define substyles for them.

**Comment by smaragdus** [comment]
I tested [textosaurus-2018.03.26-f605498-win64.7z](textosaurus-2018.03.26-f605498-win64.7z) with [Monokai Neo](https://github.com/skylerlee/monokai-neo-syntax) theme, using some sample C++ code snippets it was fine, but with sample Pascal code snippets it was not what I expected to see. So I suppose it is not worth wasting time with themes. So please feel free to close this issue.

**Comment by martinrotter** [comment]
This is because I did not add full substyles to Pascal syntax in Textosaurus. I will do, then I will close.

> So I suppose it is not worth wasting time with themes.

So you think themes in Textosaurus are unusable? Are you not happy? Ellaborate...

**Comment by martinrotter** [comment]
Added Pascal full styling information. Please check.

**Comment by martinrotter** [comment]
![screenshot 2018-03-28 07 09 17](https://user-images.githubusercontent.com/1255302/38009915-f2bd95ec-3256-11e8-8a18-651504fd8277.png)

**Comment by smaragdus** [comment]
@martinrotter 

> So you think themes in Textosaurus are unusable? Are you not happy? Ellaborate...

Just the opposite- if I thought so I would not have suggested to add more themes. I just supposed that porting themes to **Textosaurus** might be unpleasant, time-consuming job having in mind that there is no one helping you with the visual department of the program. If it happens that you have more free time in the future you may add more themes provided that you find ones that you like and you feel they belong to **Textosaurus**.

I tested **Textosaurus** version [2018.03.26-c3a9056](https://transfer.sh/r0bqB/textosaurus-2018.03.26-c3a9056-win64.7z) with Pascal language and it looks good, screen:

![textosaurus 2018 03 26-c3a9056 - 2018-03-29 - pascal - 001](https://user-images.githubusercontent.com/9025757/38068477-00725d4e-331a-11e8-8094-ea48819f7a06.png)

I also put some sample Python code, it also seems fine, screen:

![textosaurus 2018 03 26-c3a9056 - 2018-03-29 - python - 001](https://user-images.githubusercontent.com/9025757/38068723-57ffdf54-331b-11e8-9df4-81f1b03e7fd5.png)

In one word- thanks!

**Question**
When I copy a chunk of text, paste it into **Textosaurus** and scroll down to end of text it does not scroll to the last line but a way down. Isn't the scrolling down supposed to be limited to the last line? Just compare **Textosaurus** to **Notepad++** for example- when text snippet is pasted into **Notepad++** the scroll-bar automatically goes to the last line and it cannot be scrolled down further, while in **Textosaurus** the scroll-bar also goes to the last line but one can scroll down a way below the last line. Is this intended behaviour or a bug?

**Comment by martinrotter** [comment]
> one can scroll down a way below the last line. Is this intended behaviour or a bug?
This is not a bug but a feature of Scintilla component. It can be changed, question is if we want to be changeable by user or not. I agree that allowing scrolling below last line of document is probably not good default behavior.

I will switch the setting for now, and maybe I can add it as switchable option in the future if there will be interest.
