### ISSUE TITLE
Searching not working. Always returns 0 results.

### ISSUE THREAD

**Issue by lenrok258** [martinrotter/textosaurus#57]
Searching not working. Always returns 0 results.

#### How to reproduce the bug?

1. Open any text file
2. Open file modal (crtl+f)
3. Search for any text present on the page

#### What is the expected result?

Result should be found.

#### What actually happened?

'Cannot find the text "foobar"' is displayed.

#### Other information (logs, see Wiki)

What is interesting occurrence cannot be find if clicking on "Find Next" button but clicking on "Count" returns value > 0.

Problem happens in each "Match mode".

OS: Ubuntu: 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
Textosaurus version:  0.9.10
No logs are created after clicking on "Find Next" button.

**Comment by lenrok258** [comment]
It happens for every file. 

Please see the attached gif. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4930985/48539902-d598fd80-e8b8-11e8-916c-2cae954075b0.gif)

**Comment by martinrotter** [comment]
Yes, does "Find Previous" or "Find All" work in same scenario?
I believe that it cannot find anything because you actually placed text cursor to the end of file, you placed it after last "foobar", thus "Find Next" cannot find anything, because it starts its search from the position of your cursor. If you place your text cursor otherwise (for example somewhere on first line) does it help?

It does not "wrap around" search so far, do you think "wrap around" should be added?

**Comment by lenrok258** [comment]
You are right! 
I would say it is a bit misleading as in most editors if the cursor is at the end of the file it starts searching from beginning. Do you consider adding such option?

Nevertheless thank you for being superb responsive and sorry for wasting your time.

**Comment by martinrotter** [comment]
I feel like adding  "Wrap search around" could make sense. Can you create separate ticket for it?

**Comment by lenrok258** [comment]
Sure, done: https://github.com/martinrotter/textosaurus/issues/60
